// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,match:8, not:18, true:26, false:28}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")SOVQPOOO[QPO'#C^QaQPOOOfQPO,58xQaQPOOOVQPO'#DPO!WQQO1G.dO#TQPO'#CnO!fQPO'#CqOfQPO'#CuO#bQQO'#CfOOQO'#DW'#DWOOQO'#DT'#DTOfQPO'#CdOOQO-E6}-E6}OOQO,59k,59kOfQPO,58|OfQPO,58}O#sQPO'#DOO$QQPO'#DXO$kQQO'#DXO!fQPO'#DXO$rQPO,59YO!fQPO'#CuO$wQQO,59]O%oQQO,59iO%zQQO,59aO&XQQO,59QOOQO'#DY'#DYO!fQPO,59bO!fQPO,59bO'OQPO,59QOOQO,59O,59OOOQO1G.h1G.hO'VQQO1G.iO'hQQO,59jO!fQPO,59jOOQO-E6|-E6|O'|QPO,59sO(UQQO,59sOOQO1G.t1G.tO(]QQO,59aOOQO1G/T1G/TOOQO1G.{1G.{O!fQPO,59gO!fQPO,59hO(nQPO1G.lOOQO1G.|1G.|O(sQQO1G.|O!fQPO1G.lO)kQQO1G.lO*YQQO1G/UO*nQPO1G/_O*vQQO1G/ROOQO1G/R1G/RO+pQQO1G/SO+zQQO1G/SO!fQPO7+$WO,VQQO,59aO,aQQO7+$WO,lQQO<<GrOOQO<<Gr<<Gr",
  stateData: "-]~OvOS~OSPO~OTRO~O}TO~ORZOX]OZZO[ZO]ZO^ZO_ZOaVOfWOhXO~Ox`OyaOtQi}Qi~ORZOZZO[ZO]ZO^ZO_ZOaVOfWOhgO~OceOdbO`{P~P!fOfnOkmOlmOmmOnoO~OctO`rXdrX~P!fOdbO`{X~OdbOfnOkmOlmOmmO~O`{X~P$YO`xO~OfnOkmOlmOmmOnea`eadeageaxeayeatea}ea~OgzOx`OyaO~Og{Ox|Oy}O~P#bOg!OOx|Oy}O~ORZOZZO[ZO]ZO^ZO_ZOaVOfWO~Oh!RO~P&dOx`OtViyVi}VigVi~OfnOkmOlmOmmO`radra~OdbO`{a~O`{a~P$YOfnOg{OkmOlmOmmO~On!ZO~OkmOlmOmmOfjinji`jidjigjixjiyjitji}ji~OfnOkmOlmOmmOtYixYiyYi}YigYi~OfnOkmOlmOmmO`ridri~OdbO`{i~OfnOkmOlmOmmOgoixoiyoi~OfnOkmOlmOmmOx|O~Ogpiypi~P+_Ox|Ogpiypi~Ox|Oy}O~P(]Og!_Ox|Oy}O~OfnOkmOlmOmmOtYyxYyyYy}YygYy~OZ~",
  goto: "$}}PP!OPPP!U!U!UP!UPPPPPPP!]PP!]PPP!]!]PPPP!q!q!U!w#VPPP#]PP#l$n$qQQOR_TZ[RX]`auZRVWX]`abegmnot|}!R!ZXlX|}!RQcVUucv!UQvdR!UwQSQR^SQURQiXQp]Qq`RraWYR]`aQdVQhWQjXQsbQweQygQ!PmQ!QnQ!SoQ!TtQ!V|Q!X}Q![!RR!^!ZRfVQkXQ!W|Q!Y}R!]!R",
  nodeNames: "⚠ Pipeline MatchState Identifier match : AndCondition OrCondition NotCondition not CmpCondition Number String true false RegExp ] [ ArrayExpression ... , UnaryExpression ArithOp ) ( ParenthesizedExpression BinaryExpression ArithOp ArithOp ArithOp CmpOp AndLogicalExpression OrLogicalExpression ParenthesizedCondition",
  maxTerm: 45,
  nodeProps: [
    ["group", -10,3,11,12,13,14,15,18,21,25,26,"Expression",-2,31,32,"LogicalExpression"],
    ["openedBy", 16,"[",23,"("],
    ["closedBy", 17,"]",24,")"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "4}~RrXY#]Z[#]pq#]rs#ntu%fuv&Zwx&`xy(Ryz(Wz{(]{|(b|}(g}!O(b!O!P(l!P!Q*W!Q!R-d!R![.U![!]0m!^!_0r!_!`0z!`!a0r!c!}%f!}#O1P#P#Q1U#R#S%f#T#U1Z#U#c%f#c#d3d#d#o%f#p#q4x$f$g#]$g;'S%f;'S;=`&T<%lO%f~#bSv~XY#]Z[#]pq#]$f$g#]~#sW[~OY#nZr#nrs$]s#O#n#O#P$b#P;'S#n;'S;=`%`<%lO#n~$bO[~~$eRO;'S#n;'S;=`$n;=`O#n~$sX[~OY#nZr#nrs$]s#O#n#O#P$b#P;'S#n;'S;=`%`;=`<%l#n<%lO#n~%cP;=`<%l#nP%kWRPtu%f!Q![%f!c!}%f#R#S%f#T#o%f$g;'S%f;'S;=`&T<%lO%fP&WP;=`<%l%f~&`Ol~~&eW[~OY&`Zw&`wx$]x#O&`#O#P&}#P;'S&`;'S;=`'{<%lO&`~'QRO;'S&`;'S;=`'Z;=`O&`~'`X[~OY&`Zw&`wx$]x#O&`#O#P&}#P;'S&`;'S;=`'{;=`<%l&`<%lO&`~(OP;=`<%l&`~(WOh~~(]Og~~(bOm~~(gOf~~(lOd~~(oQ!O!P(u!Q![)Q~(xP!O!P({~)QOc~~)VSZ~!Q![)Q!g!h)c#R#S)Q#X#Y)c~)fS{|)r}!O)r!Q![){#R#S){~)uQ!Q![){#R#S){~*QQZ~!Q![){#R#S){R*]WkQOY*uZ!P*u!Q!}*u!}#O,O#O#P,}#P;'S*u;'S;=`-^<%lO*uP*zX_POY*uZ!P*u!P!Q+g!Q!}*u!}#O,O#O#P,}#P;'S*u;'S;=`-^<%lO*uP+lU_P#Z#[+g#]#^+g#a#b+g#g#h+g#i#j+g#m#n+gP,RVOY,OZ#O,O#O#P,h#P#Q*u#Q;'S,O;'S;=`,w<%lO,OP,kSOY,OZ;'S,O;'S;=`,w<%lO,OP,zP;=`<%l,OP-QSOY*uZ;'S*u;'S;=`-^<%lO*uP-aP;=`<%l*u~-iXZ~!O!P)Q!Q![.U!g!h)c#R#S.U#U#V.r#X#Y)c#b#c.m#c#d/a#l#m/x~.ZUZ~!O!P)Q!Q![.U!g!h)c#R#S.U#X#Y)c#b#c.m~.rOZ~~.uR!Q!R/O!R!S/O#R#S/O~/TSZ~!Q!R/O!R!S/O#R#S/O#b#c.m~/dQ!Q!Y/j#R#S/j~/oRZ~!Q!Y/j#R#S/j#b#c.m~/{S!Q![0X!c!i0X#R#S0X#T#Z0X~0^TZ~!Q![0X!c!i0X#R#S0X#T#Z0X#b#c.m~0rOT~~0wPn~!_!`0z~1POn~~1UOa~~1ZO`~R1`YRPtu%f!Q![%f!c!}%f#R#S%f#T#b%f#b#c2O#c#o%f$g;'S%f;'S;=`&T<%lO%fR2TYRPtu%f!Q![%f!c!}%f#R#S%f#T#W%f#W#X2s#X#o%f$g;'S%f;'S;=`&T<%lO%fR2zWxQRPtu%f!Q![%f!c!}%f#R#S%f#T#o%f$g;'S%f;'S;=`&T<%lO%fR3iYRPtu%f!Q![%f!c!}%f#R#S%f#T#f%f#f#g4X#g#o%f$g;'S%f;'S;=`&T<%lO%fR4`WyQRPtu%f!Q![%f!c!}%f#R#S%f#T#o%f$g;'S%f;'S;=`&T<%lO%f~4}O}~",
  tokenizers: [0, 1],
  topRules: {"Pipeline":[0,1]},
  specialized: [{term: 3, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 563
})
